# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 15:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20170501_1739'),
        ('timetables', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='time',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.RemoveField(
            model_name='event',
            name='courses',
        ),
        migrations.AddField(
            model_name='event',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.Activity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='weeks',
            field=models.CharField(default=1, max_length=127, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EventCategory',
        ),
    ]
