# Generated by Django 2.2 on 2019-05-06 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Course'),
        ),
        migrations.AlterField(
            model_name='requirementevent',
            name='end',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='requirementevent',
            name='start',
            field=models.CharField(max_length=8),
        ),
    ]
