# Generated by Django 2.2 on 2019-05-06 02:32

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='status',
            field=django_fsm.FSMField(choices=[('NEW', 'New'), ('WIP', 'Work in progress'), ('RFM', 'Ready for merge'), ('MER', 'Merged'), ('PFT', 'Published for teachers'), ('PPV', 'Publish public version')], default='NEW', max_length=3, protected=True),
        ),
    ]
