# Generated by Django 2.2.1 on 2019-05-19 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0002_auto_20190506_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='collision',
            name='timetable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timetables.Timetable'),
            preserve_default=False,
        ),
    ]
