# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20170503_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='RoomEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Equipment')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='equipment',
            field=models.ManyToManyField(through='school.RoomEquipment', to='school.Equipment'),
        ),
    ]
