# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20170503_1717'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roomequipment',
            unique_together=set([('room', 'equipment')]),
        ),
    ]
