# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20170503_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycategory',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
