# Generated by Django 2.1 on 2019-05-03 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20190501_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitycategory',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='activitycategory',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='activitycategory',
            name='color',
            field=models.CharField(max_length=7, null=True, validators=[django.core.validators.RegexValidator('#[0-9a-fA-F]{6}', 'Color has to be in hexadecimal format.')]),
        ),
        migrations.AddField(
            model_name='activitycategory',
            name='name_sk',
            field=models.CharField(default='', max_length=300, unique=True),
            preserve_default=False,
        ),
    ]
