# Generated by Django 2.1 on 2019-04-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fei', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='auto_drop_schema',
            field=models.BooleanField(default=True),
        ),
    ]
