# Generated by Django 2.1 on 2019-05-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fei', '0002_version_auto_drop_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='title_after',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='title_before',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
