# Generated by Django 2.2 on 2019-05-06 03:33

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('fei', '0004_auto_20190506_0432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='is_active',
        ),
        migrations.AddField(
            model_name='version',
            name='status',
            field=django_fsm.FSMField(choices=[('NEW', 'New'), ('WIP', 'Work in progress'), ('PUBLIC', 'Published'), ('HIDDEN', 'Hidden')], default='NEW', max_length=6, protected=True),
        ),
    ]
