# Generated by Django 2.2.1 on 2019-05-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fei', '0005_auto_20190506_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='title_after',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='title_before',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
