# Generated by Django 2.2.1 on 2019-05-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeiGroups',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nazov', models.CharField(blank=True, max_length=1500, null=True)),
                ('skratka', models.CharField(blank=True, max_length=1601, null=True)),
                ('nadriadena_skupina', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '"PRENOS"."FEI_GROUPS"',
                'managed': False,
            },
        ),
    ]
