# Generated by Django 2.2.1 on 2019-05-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fei_importexport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPredmetyFei',
            fields=[
                ('obdobie', models.CharField(max_length=100)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('garantujuce_pracovisko', models.BigIntegerField()),
                ('garant', models.BigIntegerField()),
                ('kod', models.CharField(max_length=10)),
                ('nazov', models.CharField(blank=True, max_length=500, null=True)),
                ('nazov_ang', models.CharField(blank=True, max_length=500, null=True)),
                ('std_ukonc', models.CharField(blank=True, max_length=10, null=True)),
                ('kredity', models.CharField(max_length=1500)),
            ],
            options={
                'db_table': '"PRENOS"."C_PREDMETY_FEI"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeiDepartments',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('skratka', models.CharField(blank=True, max_length=20, null=True)),
                ('nazov', models.CharField(blank=True, max_length=1000, null=True)),
                ('nadriadene_prac', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': '"PRENOS"."FEI_DEPARTMENTS"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeiEquipments',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nazov', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': '"PRENOS"."FEI_EQUIPMENTS"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeiRooms',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nazov', models.CharField(max_length=20)),
                ('kapacita', models.BigIntegerField(blank=True, null=True)),
                ('typ', models.BigIntegerField(blank=True, null=True)),
                ('pracovisko', models.BigIntegerField()),
            ],
            options={
                'db_table': '"PRENOS"."FEI_ROOMS"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeiRoomsEquipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miestnost', models.BigIntegerField()),
                ('pomocka', models.BigIntegerField()),
                ('pocet', models.CharField(max_length=1500)),
            ],
            options={
                'db_table': '"PRENOS"."FEI_ROOMS_EQUIPMENTS"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeiRoomtypes',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nazov', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '"PRENOS"."FEI_ROOMTYPES"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeiSubjects',
            fields=[
                ('obdobie', models.CharField(blank=True, max_length=100, null=True)),
                ('id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('kod', models.CharField(blank=True, max_length=10, null=True)),
                ('nazov', models.CharField(blank=True, max_length=500, null=True)),
                ('pracovisko', models.BigIntegerField(blank=True, null=True)),
                ('std_ukonc', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': '"PRENOS"."FEI_SUBJECTS"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeiSubjectsUsers',
            fields=[
                ('predmet', models.BigIntegerField(blank=True, null=True)),
                ('ais_id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('rola', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': '"PRENOS"."FEI_SUBJECTS_USERS"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeiUsers',
            fields=[
                ('ais_id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('login', models.CharField(blank=True, max_length=20, null=True)),
                ('meno', models.CharField(blank=True, max_length=50, null=True)),
                ('priezvisko', models.CharField(blank=True, max_length=70, null=True)),
                ('tituly_pred', models.CharField(blank=True, max_length=300, null=True)),
                ('tituly_za', models.CharField(blank=True, max_length=300, null=True)),
                ('karta', models.CharField(blank=True, max_length=32767, null=True)),
            ],
            options={
                'db_table': '"PRENOS"."FEI_USERS"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeiUsersDepartments',
            fields=[
                ('ais_id', models.BigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('pracovisko', models.FloatField(blank=True, null=True)),
                ('typ_pracovneho_pomeru', models.CharField(blank=True, max_length=9, null=True)),
            ],
            options={
                'db_table': '"PRENOS"."FEI_USERS_DEPARTMENTS"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeiUsersGroups',
            fields=[
                ('ais_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('skupina', models.IntegerField(blank=True, null=True)),
                ('kruzok', models.CharField(blank=True, max_length=1500, null=True)),
                ('metoda', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': '"PRENOS"."FEI_USERS_GROUPS"',
                'managed': False,
            },
        ),
    ]
